(()=>{
'use strict';
const KEY='bookflix_v4';
const $=id=>document.getElementById(id);
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const seeds=[['Neuromancer','William Gibson','science-fiction,cyberpunk,technologie,complexe','0441569595'],['Dune','Frank Herbert','science-fiction,univers,politique,complexe','0441172717'],['1984','George Orwell','dystopie,politique,sombre,classique','0451524934'],['Ubik','Philip K. Dick','science-fiction,etrange,realite,complexe','0547572176'],['La Horde du Contrevent','Alain Damasio','science-fiction,univers,aventure,complexe','2070418078'],['Fondation','Isaac Asimov','science-fiction,univers,politique,classique','0553293354'],['Silo','Hugh Howey','science-fiction,dystopie,sombre,mystere','1476733953'],['Le Nom du vent','Patrick Rothfuss','fantasy,univers,aventure,complexe','0756404746'],['Le Trone de fer','George R. R. Martin','fantasy,politique,sombre,univers','0553573403'],['Fahrenheit 451','Ray Bradbury','dystopie,politique,classique,sombre','1451678186']].map(x=>({title:x[0],author:x[1],tags:x[2].split(','),cover:'https://covers.openlibrary.org/b/isbn/'+x[3]+'-M.jpg',source:'seed'}));
let raw={};try{raw=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{}
const S={selected:Array.isArray(raw.selected)?raw.selected:[],saved:Array.isArray(raw.saved)?raw.saved:[],ratings:raw.ratings||{},hidden:Array.isArray(raw.hidden)?raw.hidden:[],history:Array.isArray(raw.history)?raw.history:[],mood:raw.mood||'',current:[],results:[]};
const save=()=>localStorage.setItem(KEY,JSON.stringify(S));
const toast=t=>{const e=$('toast');if(!e)return;e.textContent=t;e.style.display='block';clearTimeout(window.__bfRecoveryToast);window.__bfRecoveryToast=setTimeout(()=>e.style.display='none',2200)};
function renderBooks(list=seeds){S.current=list;$('books').innerHTML=list.length?list.map((b,i)=>`<article class="book ${S.selected.some(x=>norm(x.title)===norm(b.title))?'sel':''}" onclick="toggle(${i})"><div class="cover" ${b.cover?`style="background-image:url('${b.cover}')"`:''}>${b.cover?'':esc(b.title)}</div>${S.selected.some(x=>norm(x.title)===norm(b.title))?'<div class="check">✓</div>':''}<small><b>${esc(b.title)}</b><br>${esc(b.author)}</small></article>`).join(''):'<div class="empty">Aucun livre trouvé.</div>';update()}
function update(){if($('chips'))$('chips').innerHTML=S.selected.map(b=>`<span class="chip">✓ ${esc(b.title)}</span>`).join('');if($('count'))$('count').textContent=S.selected.length+' / 3 minimum';if($('build'))$('build').disabled=S.selected.length<3}
window.toggle=i=>{const b=S.current[i];if(!b)return;const n=S.selected.findIndex(x=>norm(x.title)===norm(b.title));if(n>=0)S.selected.splice(n,1);else if(S.selected.length<8)S.selected.push(b);else return toast('Maximum 8 livres.');save();renderBooks(S.current)};
window.view=v=>{document.querySelectorAll('.view').forEach(x=>x.classList.remove('on'));$(v)?.classList.add('on');$('nd')?.classList.toggle('on',v==='discover');$('nl')?.classList.toggle('on',v==='library');if(v==='library')renderLibrary()};
window.searchBooks=async()=>{const q=$('q')?.value.trim();if(!q)return renderBooks(seeds);$('books').style.opacity='.45';try{const u='/api/openlibrary/search?'+new URLSearchParams({q,limit:'24',fields:'key,title,author_name,cover_i,subject,first_publish_year,edition_count,language'});const j=await (await fetch(u)).json();const seen=new Set();const list=(j.docs||[]).map(d=>({title:d.title||'Sans titre',author:(d.author_name||['Auteur inconnu'])[0],tags:(d.subject||[]).map(norm).filter(x=>x.length>2).slice(0,24),cover:d.cover_i?`https://covers.openlibrary.org/b/id/${d.cover_i}-M.jpg`:'',year:d.first_publish_year||'',edition_count:d.edition_count||0,key:d.key||'',source:'openlibrary'})).filter(b=>{const k=norm(b.title+'|'+b.author);if(seen.has(k))return false;seen.add(k);return true});renderBooks(list);if(!list.length)toast('Aucun livre trouvé.')}catch(e){toast('La recherche est momentanément indisponible.')}finally{$('books').style.opacity='1'}};
window.build=()=>{if(S.selected.length<3)return toast('Choisis au moins 3 livres.');$('profileBox').style.display='block';$('profile').innerHTML='<div class="trait"><b>🧬 Profil prêt</b><span>Basé sur tes '+S.selected.length+' choix</span></div>';recommend()};
window.surprise=()=>{S.selected=[...seeds].sort(()=>Math.random()-.5).slice(0,3);save();renderBooks(seeds);build();toast('Profil surprise prêt.')};
async function recommend(){if(S.selected.length<3)return toast('Choisis au moins 3 livres.');S.mood=$('mood')?.value||'';save();$('results').innerHTML='<div class="empty">Je cherche…</div>';$('profileBox').style.display='block';let docs=[];try{const q=(S.mood||S.selected.map(x=>(x.tags||[]).slice(0,2).join(' ')).join(' ')).trim()||'science fiction';const r=await fetch('/api/openlibrary/search?'+new URLSearchParams({q,lang:'fr',limit:'32',fields:'key,title,author_name,cover_i,subject,first_publish_year,edition_count'}));const j=await r.json();docs=(j.docs||[]).map(d=>({title:d.title||'Sans titre',author:(d.author_name||['Auteur inconnu'])[0],tags:(d.subject||[]).map(norm).slice(0,20),cover:d.cover_i?`https://covers.openlibrary.org/b/id/${d.cover_i}-M.jpg`:'',year:d.first_publish_year||'',edition_count:d.edition_count||0,key:d.key||''}));}catch{}docs=[...docs,...seeds];const selected=new Set(S.selected.map(x=>norm(x.title)));const seen=new Set();S.results=docs.filter(b=>!selected.has(norm(b.title))&&!S.hidden.includes(b.title)).filter(b=>{const k=norm(b.title+'|'+b.author);if(seen.has(k))return false;seen.add(k);return true}).slice(0,8);S.history.unshift({date:Date.now(),mood:S.mood,results:S.results.slice(0,5)});S.history=S.history.slice(0,10);save();renderResults(S.results);if($('status'))$('status').textContent=S.results.length+' suggestions'}
window.recommend=recommend;
function renderResults(a){$('results').innerHTML=a.length?a.map(b=>{const r=S.ratings[b.title]||0;return `<article class="result"><div class="mini" ${b.cover?`style="background-image:url('${b.cover}')"`:''}>${b.cover?'':esc(b.title)}</div><div><h3>${esc(b.title)}</h3><div class="meta">${esc(b.author)}${b.year?' · '+esc(b.year):''}</div><div class="stars">${[1,2,3,4,5].map(n=>`<button class="star ${n<=r?'on':''}" onclick="rate('${esc(b.title).replace(/'/g,"\\'")}',${n})">★</button>`).join('')}</div><div class="ra"><button class="btn ghost tiny" onclick="saveBook('${esc(b.title).replace(/'/g,"\\'")}')">＋ Sauvegarder</button><button class="btn ghost tiny" onclick="hideBook('${esc(b.title).replace(/'/g,"\\'")}')">Pas pour moi</button></div></div></article>`}).join(''):'<div class="empty">Pas assez de pistes.</div>'}
window.rate=(t,n)=>{S.ratings[t]=n;save();toast('Note enregistrée · '+n+'/5');renderResults(S.results)};
window.saveBook=t=>{const b=S.results.find(x=>x.title===t)||seeds.find(x=>x.title===t);if(b&&!S.saved.some(x=>norm(x.title)===norm(b.title)))S.saved.unshift(b);save();toast('Ajouté à ta bibliothèque.');renderResults(S.results)};
window.hideBook=t=>{if(!S.hidden.includes(t))S.hidden.push(t);S.results=S.results.filter(x=>x.title!==t);save();renderResults(S.results);toast('Compris — je l’écarte.')};
function renderLibrary(){const all=[...S.saved.map(x=>({...x,type:'favori'})),...S.selected.map(x=>({...x,type:'profil'}))];$('libraryGrid').innerHTML=all.length?all.map(b=>`<article class="lib"><div class="cover" ${b.cover?`style="background-image:url('${b.cover}')"`:''}></div><span class="badge">${b.type==='favori'?'♥ Favori':'Profil'}</span><small><b>${esc(b.title)}</b><br>${esc(b.author)}</small></article>`).join(''):'<div class="empty" style="grid-column:1/-1">Ta bibliothèque est vide.</div>'}
function boot(){if(typeof window.searchBooks==='function'&&$('books')?.children.length)return;window.renderBooks=renderBooks;renderBooks(seeds);if($('q'))$('q').onkeydown=e=>{if(e.key==='Enter')window.searchBooks()};if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
